### ISSUE TITLE
Local implementation.

### ISSUE THREAD

**Issue by XarsEvandor** [asigalov61/Allegro-Music-Transformer#7]
Hello, I am working on a project and I would like to implement this amazing transformer as a module. 
I would like to create a local implementation of this project using conda on windows. 
Ideally, I would also love some documentation on all the different parameters that dictate the behavior of the model. My ultimate goal would be to import a seed midi and have the model produce an enhanced version of it, instead of continuing the melody. 
Let me know if any of these are possible, any help would be greately appreciated!

**Comment by asigalov61** [comment]
@XarsEvandor Thank you for writing and for your interest in this project :)

I would recommend to start with installing standard Anaconda distribution from Anaconda web site, which comes with JupyterLab notebooks support. This way you can just use the colabs from the repo to run it on windows. All you have to do is to download the colabs from the repo and load them into your local Anaconda JupyterLab.

You do not need to do or change anything, except the paths in the colabs and all requirements/prerequisites are already in the colab so that you can install it from there.

I hope this makes sense and I hope it can get you started. But feel free to let me know if you have problems/need more help.

Alex

**Comment by XarsEvandor** [comment]
Sorry, I wasn't clear enough. I want to transform the project into raw python instead of a notebook. This is because it will have to interact with many other modules in my project. I also want to learn if it is possible to "rewrite" midi seed instead of continuing it. Thanks!

**Comment by asigalov61** [comment]
@XarsEvandor Yes, you can definitely turn this project into standard Python modules instead of the notebooks. I specifically provide the py versions of colabs so that the people can do it. For examples, here is the original Allegro colab but as a Python module: https://github.com/asigalov61/Allegro-Music-Transformer/blob/main/allegro_music_transformer.py

Please note that this module was auto-generated by Google Colab so it needs some clean-up and adjustments, but otherwise I think it is what you need.

In regard to your other question: Yes, auto-regressive models can do some degree of "rewriting". Please see Allegro features colab/code:
https://colab.research.google.com/github/asigalov61/Allegro-Music-Transformer/blob/main/Allegro_Music_Transformer.ipynb

Last section of this colab offers inpainting option, where you can inpaint desired parts of the MIDI file. You can also further modify it to make it more advanced.

I hope this helps and answers your questions.

Sorry for the misunderstanding :)

Alex

**Comment by XarsEvandor** [comment]
Thank you, Alex!
